export default {
    products: [
        {
            _id: '1',
            name: 'Slim shirts',
            category: 'shirts',
            Image: '/images/product-1.jpg',
            price: 600,
            brand: 'Hiskywin',
            rating:4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Zip sweatshirt',
            category: 'shirts',
            Image: '/images/product-2.jpg',
            price: 1200,
            brand: 'NIKE',
            rating: 5,
            numReviews: 51,
        },
        {
            _id: '3',
            name: 'Nike Mens Long Sleeve Hoodie',
            category: 'shirts',
            Image: '/images/product-3.jpg',
            price: 1200,
            brand: 'NIKE',
            rating:4,
            numReviews: 45,
        },
        {
            _id: '4',
            name: 'Under Armour Sweat Pants',
            category: 'Pants',
            Image: '/images/product-4.jpg',
            price: 1350,
            brand: 'Under Armour',
            rating:2.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Champion Mens Graphic Powerblend Fleece Jogger',
            category: 'Pants',
            Image: '/images/product-5.jpg',
            price: 2100,
            brand: 'Champion',
            rating:3.5,
            numReviews: 89,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Aelfric Eden Mens Pants long',
            category: 'Pants',
            Image: '/images/product-6.jpg',
            price: 1800,
            brand: 'Aelfric Eden',
            rating:4.5,
            numReviews: 45,
            countInStock: 6,
        },
    ],
};